name: internship
version: 0.1.0.0
github: "githubuser/internship"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2026 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/internship#readme>

dependencies:
  - base >= 4.7 && < 5
  - split
  - containers
  - utf8-string
  - hasktorch
  - hasktorch-tools
  - nlp-tools
  - cassava
  - bytestring
  - unordered-containers
  - hashable
  - aeson

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src
    - Session5/src

executables:
  internship-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - internship

  session3-linear-regression:
    main: LinearRegression.hs
    source-dirs: Session3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is LinearRegression
    dependencies:
      - internship

  session-3-multiple-regression:
    main: MultipleRegression.hs
    source-dirs: Session3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is MultipleRegression
    dependencies:
      - internship

  session-3-graduate-admission-linear:
    main: GraduateAdmissionLinear.hs
    source-dirs: Session3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is GraduateAdmissionLinear
    dependencies:
      - internship

  session-4-perceptron-and-gate:
    main: PerceptronAndGate.hs
    source-dirs: Session4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is PerceptronAndGate
    dependencies:
      - internship

  session-4-mlp-xor:
    main: MlpXor.hs
    source-dirs: Session4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is MlpXor
    dependencies:
      - internship

  session-5-evaluation:
    main: Evaluation.hs
    source-dirs: Session5/src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Evaluation
    dependencies:
      - internship

  session-5-admit:
    main: Admit.hs
    source-dirs: Session5
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Admit
    dependencies:
      - internship

  session-5-titanic:
    main: Titanic.hs
    source-dirs: Session5
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Titanic
    dependencies:
      - internship

  session-6-word2vec:
    main: Word2vec.hs
    source-dirs: Session6
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Word2vec
    dependencies:
      - internship

  session-6-eval:
    main: Eval.hs
    source-dirs: Session6
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Eval
    dependencies:
      - internship

  session-7-rnn:
    main: Rnn.hs
    source-dirs: Session7
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Rnn
    dependencies:
      - internship

tests:
  internship-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - internship
